version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: tibo
      POSTGRES_PASSWORD: tibo
      POSTGRES_DB: intersystoDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
